### ISSUE TITLE
Build fails due to missing macros.xml

### ISSUE THREAD

**Issue by rmaavnii** [archiecobbs/jibx-bindings#1]
Hello - I forked your repository and attempted to build it (ant) however it fails immediately due to missing file macros.xml

`.../jibx-bindings/build.xml:12: Cannot find .../jibx-bindings/src/build/macros.xml imported from .../jibx-bindings/build.xml`

**Comment by archiecobbs** [comment]
Oops, my apologies. Should be fixed by 56adcc6.
